GGBE-137-user-live-api-fix-event
42organization/42gg.server.dev.v2 pull request #119
Opened 2023-06-08 08:26 UTC by greatSweetMango

## 📌 개요 
  - DB PChange 테이블에 is_checked 컬럼 추가했습니다. 해당 컬럼이 false일 경우 envet는 game으로 전송되고 재요청시에는 해당 컬럼이 true로 바뀌어 null로 전송됩니다. 
 ## 💻 작업사항 
  -
 ## ✅ 변경로직 
  -

2023-06-08 09:04 UTC, wken5577 approved these changes

2023-06-08 09:08 UTC, FeFe2200 requested changes

2023-06-08 09:10 UTC, kmularise commented on src/main/java/com/gg/server/domain/pchange/service/PChangeService.java
> +        pChangeRepository.save(new PChange(game, user, pppResult, is_checked));
카멜 케이스로 바꿔주세요!

2023-06-09 03:48 UTC, greatSweetMango commented on src/main/java/com/gg/server/domain/user/service/UserService.java
> +        System.out.println("MANGO : WAHTFJSLKFJSDKJF");
허걱 안뺐네요

2023-06-12 04:11 UTC, greatSweetMango commented on src/main/java/com/gg/server/domain/pchange/service/PChangeService.java
> +        pChangeRepository.save(new PChange(game, user, pppResult, is_checked));
수정했습니다!

2023-06-12 04:11 UTC, merged