GGbe 31 announcement curd
42organization/42gg.server.dev.v2 pull request #30
Opened 2023-05-11 11:19 UTC by FeFe2200

## 📌 개요 
  - 관리자 공지사항 조회 pingpong/admin/announcement?page=${currentpage}&size=${recordSize}
 ## 💻 작업사항 
  -
 ## ✅ 변경로직 
  -

2023-05-11 11:23 UTC, greatSweetMango approved these changes
확인했습니다

2023-05-12 02:58 UTC, kmularise requested changes

2023-05-12 03:02 UTC, FeFe2200 commented on src/main/java/com/gg/server/admin/announcement/dto/AnnouncementAdminResponseDto.java
> +    private String conten;
수정했습니다~!

2023-05-12 03:02 UTC, FeFe2200 commented on src/main/java/com/gg/server/admin/announcement/controller/AnnouncementAdminController.java
> +@Slf4j
삭제했습니다~!

2023-05-12 03:03 UTC, kmularise approved these changes
확인했습니다!

2023-05-12 03:04 UTC, merged