✨ [Feature] 토너먼트 게임 결과 등록 API 추가
42organization/42gg.server.dev.v2 pull request #371
Opened 2023-12-11 13:15 UTC by Newsujin

## 📌 개요
  - 토너먼트 게임 결과 등록 API 구현

 ## 💻 작업사항
 ### GameController
  - 토너먼트 게임 결과 등록 컨트롤러 구현
  - `InvalidParameterException`: 양 팀 점수의 합이 3 이상이거나 양 팀의 점수가 동일할 경우 throw
 ### GameService
  - `findGameWithPessimisticLockById`: `DB`에 `Lock`을 걸고 Id를 통해 Game을 찾는 메소드
  - `GameStatusNotMatchedException`: 게임의 상태가 `WAIT`, `LIVE`가 아닐 경우 throw
  - `updateScore`: 토너먼트 게임 결과를 업데이트 하는 메소드
    - 게임 점수가 -1일 경우(입력되지 않은 경우), 각 팀 점수 입력
    - 토너먼트 결승전 게임일 경우, 토너먼트의 상태를 END로 변경
    - `InvalidParameterException`: `Dto`에 담긴 `myTeamUser`와 파라미터를 통해 받은 `User`의 Id가 일치하지 않을 경우 throw
  - `ScoreAlreadyEnteredException`: 점수가 이미 입력되어 있을 경우 throw
 ### GameControllerTest
  - 토너먼트 게임 점수 결과 입력 테스트
    - 입력 성공
    - 잘못된 Game Id
    - 잘못된 Team Id
    - 잘못된 점수
    - 잘못된 Game Status
    - 이미 점수 입력이 완료된 게임
    - 잘못된 Team User
 ### Game Entity
  - Game `Builder` 생성
### Exception
  - `GameStatusNotMatchedException`: 게임 상태가 WAIT, LIVE가 아닌 경우의 exception
  - `ScoreAlreadyEnteredException`: 점수 입력이 완료된 게임인 경우의 exception
 ### Dto
  - `TournamentResultReqDto`: 토너먼트 게임 결과 `RequestDto`
  - `requestDto`, `responseDto` 폴더 분리
 ## ✅ 변경로직
  -
 ## 💡Issue 번호
 - close #346 
 - close #

2023-12-11 15:28 UTC, Kimhan-nah commented on src/test/java/com/gg/server/domain/game/GameControllerTest.java
> +//        rankRedisService.updateRankRedis(teams.get(0), teams.get(1), game2);
헉 이거 왜 전체 주석처리죠??

2023-12-12 01:37 UTC, Kimhan-nah commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +        updateScore(game, scoreDto, userId);
updateScore 실패시 false return 하던데 이거에 대한 처리가 없는 것 같습니다

2023-12-12 01:38 UTC, Kimhan-nah commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    private void updateScore(Game game, TournamentResultReqDto scoreDto, Long userId) {
함수 매개변수까지 동일한 updateScore 함수가 이미 있느데 이게 가능한가요...??

2023-12-12 01:40 UTC, Kimhan-nah commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    private void updateScore(Game game, TournamentResultReqDto scoreDto, Long userId) {
내용이 거의 동일한 것 같은데 따로 분리해야되는 이유가 있나요?

2023-12-12 02:20 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +        updateScore(game, scoreDto, userId);
이전에 존재하는 동일한 이름의 updateScore 메소드를 말씀하신 것 같은데, 제가 만든 메소드는 void 라서 처리하지 않아도 됩니다!

2023-12-12 02:20 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    private void updateScore(Game game, TournamentResultReqDto scoreDto, Long userId) {
함수 매개변수가 달라서 추가가 가능했습니다! (저는 TournamentResultReqDto를 사용했고, 다른 메소드에서는 RankResultReqDto를 사용했습니다)
기존에 있는 updateScore와 다른 점은 PPP, 티어의 변화가 없다는 점과 토너먼트 결승전일 경우 토너먼트를 END 상태로 전환하는 부분입니다!
헷갈릴 수 있으니 해당 함수 이름 updateTournamentGameScore로 변경하도록 하겠습니다!

2023-12-12 02:22 UTC, Newsujin commented on src/test/java/com/gg/server/domain/game/GameControllerTest.java
> +//        rankRedisService.updateRankRedis(teams.get(0), teams.get(1), game2);
이전에 존재하던 BeforeEach 코드인데 해당 부분에서 에러가 터져서 주석 처리해두었습니다!

2023-12-12 03:30 UTC, Kimhan-nah commented on src/test/java/com/gg/server/domain/game/GameControllerTest.java
> +//        rankRedisService.updateRankRedis(teams.get(0), teams.get(1), game2);
이부분은 그럼 승철님 pr merge 후에 수정하시면 될 거 같아용

2023-12-12 03:31 UTC, Newsujin commented on src/test/java/com/gg/server/domain/game/GameControllerTest.java
> +//        rankRedisService.updateRankRedis(teams.get(0), teams.get(1), game2);
넵 확인했습니당

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/GameController.java
> +        if (reqDto.getMyTeamScore() + reqDto.getEnemyTeamScore() > 3 || reqDto.getMyTeamScore() == reqDto.getEnemyTeamScore()) {
1대0 결과 입력하면 해당 조건문을 통과하는것 같아보입니다! 통과되어야 하는 점수의 종류는 2:0, 2:1 로 보여서 질문 남깁니다

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/GameController.java
> +        return new ResponseEntity<Void>(HttpStatus.CREATED);
저희 ResponseEntity.ok().body() 같은 형식으로 작성하기로 하지않았었나요???

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/data/Game.java
> +    @Builder
id 값을 지정하는 빌더가 꼭 필요한건가요?? db에 들어갈때 자동으로 아이디가 생성되기도 하고 따로 지정해주는 이유가 있는지 궁금합니다

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    public void createTournamentResult(TournamentResultReqDto scoreDto, Long userId) {
매서드명이 좀 헷갈릴 수 도 있을것 같은데 createTournamentGameResult 은 별로일까요?

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    private Boolean updateTournamentGameScore(Game game, RankResultReqDto scoreDto, Long userId) {
이거는 기존 코드같은데 이름에 tournament가 왜 들어갔는지 궁금합니다. 264번째 매서드랑 이름이 겹쳐보이기도 합니다.

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +        } else {
위의 if 문에서 throw 하는데 여기서 else 문으로 감싸야 하는지 의문입니다!

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +                Optional<TournamentGame> tournamentGame = tournamentGameRepository.findById(scoreDto.getGameId());
tournamentGameRepository.findById() 에서 scoreDto.getGameId() 는 게임 아이디 인데 .findByGameId() 와 같은 매서드로 찾아야 하지 않나요?

2023-12-12 03:52 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +            } else {
토너먼트 게임이 결승이 아닌경우 다 else 로 빠져서 throw 되는게 맞는건가요?? 점수가 이미 입력된 경우 team 에 점수가 입력되어있는 상태인것 같아보이는데 이부분을 확인하는 곳이없어 보여서 여쭤봅니다!

2023-12-12 03:55 UTC, Kimhan-nah commented on src/main/java/com/gg/server/domain/game/GameController.java
> +        return new ResponseEntity<Void>(HttpStatus.CREATED);
이부분은 이슈 따로 파져있어서 한꺼번에 수정해도 될 거 같아용

2023-12-12 03:55 UTC, Kimhan-nah commented on src/main/java/com/gg/server/domain/game/GameController.java
> +        return new ResponseEntity<Void>(HttpStatus.CREATED);
아 지금 수정해도 상관 없긴한데 game 쪽이 지금 다 수진님처럼 반환하고 있습니닷

2023-12-12 03:57 UTC, Kimhan-nah commented on src/main/java/com/gg/server/domain/game/data/Game.java
> +    @Builder
생성자 파라미터에 id 제외하면 좋을 거 같군요?? 근데 영선님이 builder 지양하라고 해서 이거도 나중에 어쩌면 수정해야될 수 있습니다 ㅎ.ㅎ

2023-12-12 04:10 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/GameController.java
> +        if (reqDto.getMyTeamScore() + reqDto.getEnemyTeamScore() > 3 || reqDto.getMyTeamScore() == reqDto.getEnemyTeamScore()) {
그렇네요! 이 부분은 기존 랭크 게임 결과 등록 코드와 동일하게 작성한 건데, 기존 코드에서도 1:0 일 때 통과하는 것으로 보입니다.
그럼 해당 부분 랭크 게임에서도 동일하게 수정하도록 하겠습니다!

2023-12-12 04:17 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    public void createTournamentResult(TournamentResultReqDto scoreDto, Long userId) {
좋습니다 ㅎㅎ 해당 이름으로 수정하겠습니다.

2023-12-12 04:17 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    private Boolean updateTournamentGameScore(Game game, RankResultReqDto scoreDto, Long userId) {
헉 제 메서드 수정하는 과정에서 동일한 이름이라서 해당 메서드도 수정이 된 것 같네요 수정해두겠습니다!

2023-12-12 04:21 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    public void createTournamentResult(TournamentResultReqDto scoreDto, Long userId) {
해당 부분 랭크 게임(createRankResult)과 노멀 게임(createNormalResult)에서도 동일한 구조로 작성되어 있어서, 형식을 동일하게 하기 위해 작성하였습니다.
토너먼트만 별개로 이름을 수정하는 쪽이 더 낫다고 생각하시나요?

2023-12-12 04:22 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +        } else {
음 그렇네요! else문을 없애는 게 더욱 깔끔해질 것 같아 보입니다. 수정하겠습니다!

2023-12-12 04:34 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +            } else {
저 else문은 결승전이 아닐 경우 들어가는 것이 아닌, 그 위에 있는 if문에서 들어갑니다! 즉 점수 입력이 완료된 상황에서 들어가게 됩니다!

2023-12-12 04:46 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +                Optional<TournamentGame> tournamentGame = tournamentGameRepository.findById(scoreDto.getGameId());
예리하십니다. 수정하였습니닷!!!

2023-12-12 04:47 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +    public void createTournamentResult(TournamentResultReqDto scoreDto, Long userId) {
제 생각에도 `Tournament`의 경우 메서드명만 보면 헷갈릴 가능성이 있어 자훈님 말씀대로 `createTournamentGameResult`로 수정하였습니다!

2023-12-12 04:48 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/GameController.java
> +        if (reqDto.getMyTeamScore() + reqDto.getEnemyTeamScore() > 3 || reqDto.getMyTeamScore() == reqDto.getEnemyTeamScore()) {
영선님께 질문 결과 랭크 게임 결과 등록 코드도 수정 원하셔서 해당 부분 수정하였습니다!

2023-12-12 04:52 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/data/Game.java
> +    @Builder
이 부분은 테스트 코드에서 유효하지 않은 아이디 입력이 들어올 경우를 대비하여 작성한 것입니다. 사실 꼭 필요한 코드는 아니라서 제거할 수 있는데 지우는 게 좋을까요?

2023-12-12 04:57 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/service/GameService.java
> +            } else {
아 제가 괄호를 잘못 봤네요 하핳

2023-12-12 04:58 UTC, SONGS4RI commented on src/main/java/com/gg/server/domain/game/data/Game.java
> +    @Builder
서비스 계층 테스트를 위한 생성자라면 필요없다고 생각합니다! 저도 비슷한 상황에서 그냥 서비스 계층 테스트를 버리고 대신 통합테스트에서 꼼꼼하게 했었습니다

2023-12-12 05:06 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/data/Game.java
> +    @Builder
넵 해당 빌더 제거 완료하였습니닷!

2023-12-12 05:08 UTC, Newsujin commented on src/main/java/com/gg/server/domain/game/GameController.java
> +        return new ResponseEntity<Void>(HttpStatus.CREATED);
맞습니다 기존 game 코드에서 전부 위와 같이 반환하여 동일하게 작성하였습니다!
그럼 나중에 저희가 작성하지 않은 game 쪽 코드들 반환 값도 수정해야겠군요!

2023-12-12 08:00 UTC, kokomong2 requested changes
전체적으로 잘 짜주셨습니다! 
하지만 제가 테스트코드에서 사용중인 부분이 변경되어서 이 부분에 대한 체크가 필요해보입니다.

2023-12-12 13:30 UTC, Newsujin commented on src/test/java/com/gg/server/utils/TestDataUtils.java
> +                .endTime(LocalDateTime.now().plusDays(1))
음 해당 부분 수정한 기억이 없는데 다시 원상복구 해놓았습니다 ㅎㅎ

2023-12-12 13:33 UTC, kokomong2 approved these changes
수정내용 확인했습니다~ 수고하셨습니다!

2023-12-12 13:36 UTC, Kimhan-nah approved these changes
수고하셨습니다. 제가 이어서 작업하면서 수정할 부분 수정하도록 하겠습니닷

2023-12-12 13:36 UTC, merged