511 feature 게임 매칭 큐 admin 페이지에서 확인 가능한 페이지 추가
42organization/42gg.server.dev.v2 pull request #525
Opened 2024-01-28 13:58 UTC by Kimhan-nah

## 📌 개요 
  -
 ## 💻 작업사항 
  -
 ## ✅ 변경로직 
  -
 ## 💡Issue 번호 
 -

2024-02-25 13:08 UTC, AYoungSn requested changes
한나님 controller dto 랑 service 단 dto 분리해주세용
- controller > request, response
- service > param, response

2024-03-04 06:59 UTC, AYoungSn approved these changes
LGTM

2024-03-08 04:51 UTC, wken5577 approved these changes
확인 완료!

2024-03-11 06:26 UTC, AYoungSn approved these changes

2024-03-11 06:27 UTC, merged