✨ [Feature] 방 상태 변경 스케쥴러
42organization/42gg.server.dev.v2 pull request #722
Opened 2024-03-11 11:33 UTC by JayJay-Kay

## 📌 개요 
  - 방 상태 변경 스케쥴러
 ## 💻 작업사항 
  - main에 @EnableScheduler 어노테이션 추가
  - RoomService에 스케쥴러 코드 추가 (FINISH, FAIL)
 ## 💡Issue 번호 
 - closed #721

2024-03-11 11:41 UTC, AYoungSn commented on gg-pingpong-api/src/main/java/gg/PingpongApiApplication.java
> +@EnableScheduling
1. Main 은 어노테이션으로 지저분해지면 읽기 어려워질 수 있다는 문제가 있어 SpringBootApplication 어노테이션을 제외한 어노테이션은 지양하는게 좋을것 같다는 생각입니다! 필요 시 설정 클래스를 추가해서 해결 가능합니다

2024-03-11 11:47 UTC, AYoungSn commented on gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
> +	@Scheduled(fixedRateString = "60000") // Every minute
스케줄러가 여기에 있는 이유가 있을까요?

2024-03-11 12:02 UTC, AYoungSn requested changes
- RoomService 클래스가 담당하고 있는 역할이 아주 많아보이는데, 이러면 나중에 코드를 보는게 어려워서 역할별로 분리해주시면 좋을것 같습니다.
- 저희 기존 스케줄러 확인 해보셨나요? 참고해보시면 좋을것 같습니다!
- 현재 update 문을 setter 처럼 쓰고 계신데, 어떤 상황에 엔티티가 변경되는지에 대해 함수를 보고 파악하기 어려울것 같다는 생각입니다. 혹시 이 부분 고민해보셨을까요?
- 현재 update 함수 호출 이후 save 바로 호출하고 계신데, 바로 호출하시는 이유가 있는지 궁금합니다.

2024-03-11 14:17 UTC, JayJay-Kay commented on gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
> +	@Scheduled(fixedRateString = "60000") // Every minute
기존 스케줄러 참고해서 수정하겠습니다

2024-03-11 14:18 UTC, JayJay-Kay commented
> * RoomService 클래스가 담당하고 있는 역할이 아주 많아보이는데, 이러면 나중에 코드를 보는게 어려워서 역할별로 분리해주시면 좋을것 같습니다.
> * 저희 기존 스케줄러 확인 해보셨나요? 참고해보시면 좋을것 같습니다!
> * 현재 update 문을 setter 처럼 쓰고 계신데, 어떤 상황에 엔티티가 변경되는지에 대해 함수를 보고 파악하기 어려울것 같다는 생각입니다. 혹시 이 부분 고민해보셨을까요?
> * 현재 update 함수 호출 이후 save 바로 호출하고 계신데, 바로 호출하시는 이유가 있는지 궁금합니다.

2024-03-12 11:06 UTC, AYoungSn commented on gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
> +import org.springframework.scheduling.annotation.Scheduled;
이 import 사용하고 있는거 맞나요?

2024-03-12 11:48 UTC, JayJay-Kay commented on gg-pingpong-api/src/main/java/gg/party/api/user/room/service/RoomService.java
> +import org.springframework.scheduling.annotation.Scheduled;
사용 안하는군요, 수정했습니다

2024-03-12 13:58 UTC, JayJay-Kay commented
곧 테스트하며 터질걸 대비해서 벌크 업데이트 쿼리 메모하겠습니다. 코드 봐주시고 제가 모르던 기능들과 해결책들 제시해주셔서 감사합니다.

2024-03-13 08:13 UTC, AreSain approved these changes
고생하셨습니다. 저희 서비스 활성화에 따른 게시글 남기기는 고민을 좀 해봐야할 것 같아요!
스케줄러는 기존 5분형식으로 되어있는데, 만약 프론트랑 상의 후 15분 단위로 나눠야할수도 있을 것 같습니다!

2024-03-13 08:55 UTC, ghyen approved these changes

2024-03-13 09:24 UTC, yes-ee commented
> 고생하셨습니다. 저희 서비스 활성화에 따른 게시글 남기기는 고민을 좀 해봐야할 것 같아요! 스케줄러는 기존 5분형식으로 되어있는데, 만약 프론트랑 상의 후 15분 단위로 나눠야할수도 있을 것 같습니다!

아까 안 그래도 몇 분 단위로 할 건지 프론트 쪽에서 물어봤는데, 나중에 다시 얘기해 봐요

2024-03-13 09:24 UTC, yes-ee approved these changes
수고하셨습니다!

2024-03-13 12:37 UTC, merged