Ggbe 37 feat admin season
42organization/42gg.server.dev.v2 pull request #8
Opened 2023-05-02 08:17 UTC by FeFe2200

## 📌 개요 
  - 관리자 시즌 리스트 조회
 ## 💻 작업사항 
  - 기존 v1 의 시즌모드 req값 제거에 따른 대응

2023-05-03 02:43 UTC, FeFe2200 commented
테스트 코드 작성 후 풀리퀘 에정

2023-05-04 06:59 UTC, AYoungSn requested changes

2023-05-04 06:59 UTC, AYoungSn commented on src/main/java/com/gg/server/admin/season/dto/SeasonAdminDto.java
> +    private Integer status;
이 status 는 왜 integer type인가요?

2023-05-04 06:59 UTC, AYoungSn commented on src/main/java/com/gg/server/admin/season/dto/SeasonAdminDto.java
> +        if (now.isAfter(season.getEndTime()))
if~else 문 함수로 빼는게 보기 편할 것 같습니다

2023-05-04 07:05 UTC, FeFe2200 commented on src/main/java/com/gg/server/admin/season/dto/SeasonAdminDto.java
> +        if (now.isAfter(season.getEndTime()))
넵, 변경할께요

2023-05-04 07:06 UTC, FeFe2200 commented on src/main/java/com/gg/server/admin/season/dto/SeasonAdminDto.java
> +    private Integer status;
기존에 integer 타입으로 값을 보내고 프론트에서도 그대로 0,1,2로 출력 하길래 integer 했습니다.
String으로 변경할까요? DB에 따로 영향을 없습니다.

2023-05-04 10:02 UTC, AYoungSn commented on src/main/java/com/gg/server/admin/season/dto/SeasonAdminDto.java
> +    private Integer status;
String 타입으로 변경하는게 좋을것같습니다

2023-05-10 03:10 UTC, AYoungSn commented on src/main/java/com/gg/server/admin/season/controller/SeasonAdminController.java
> +    public void createSeason(@Valid @RequestBody SeasonCreateRequestDto seasonCreateReqeustDto) {
status code 201 전달되게 바꿔주세요

2023-05-10 03:25 UTC, AYoungSn commented on src/main/java/com/gg/server/admin/rank/service/RankRedisAdminService.java
> +            rankRedisRepository.addToZSet(redisZSetKey, user.getId(), seasonAdminDto.getStartPpp());
ranking 리스트에 빼주세요!

2023-05-10 08:05 UTC, FeFe2200 commented on src/main/java/com/gg/server/admin/rank/service/RankRedisAdminService.java
> +            rankRedisRepository.addToZSet(redisZSetKey, user.getId(), seasonAdminDto.getStartPpp());
완료했습니다

2023-05-10 08:51 UTC, FeFe2200 commented on src/main/java/com/gg/server/admin/season/controller/SeasonAdminController.java
> +    public void createSeason(@Valid @RequestBody SeasonCreateRequestDto seasonCreateReqeustDto) {
변경했습니다.

2023-05-11 02:07 UTC, FeFe2200 commented on src/main/java/com/gg/server/admin/season/dto/SeasonAdminDto.java
> +    private String status;
????

2023-05-11 08:49 UTC, greatSweetMango approved these changes
확인했습니다!

2023-05-12 03:05 UTC, merged