✨ [Feature] 개인 상세 조회 API
42organization/42gg.server.dev.v2 pull request #877
Opened 2024-07-05 11:27 UTC by kimjieun0301

## 📌 개요 
  - agenda profile detail 조회
 ## 💻 작업사항 
  - agenda profile detail 조회
 ## 💡Issue 번호 
 - closed #852

2024-07-08 04:43 UTC, AreSain submitted a review, later dismissed
고생하셨습니다. 코드 사이사이에 주석 넣는것과 위에 통합으로 쓰는것 중 어떤걸로 할지 정해보면 좋을 것 같아요

2024-07-08 10:15 UTC, yhames requested changes

2024-07-08 10:15 UTC, yhames commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
> +@Transactional(readOnly = true)
개인 프로필 변경 API가 추가될 수 있기 때문에 클래스에 `@Transactional`을 붙이는 것보다는 각 메서드 별로 추가하는게 좋을 것 같습니다.

2024-07-08 10:29 UTC, kimjieun0301 commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileFindService.java
> +@Transactional(readOnly = true)
코멘트 감사합니다. 변경하고 커밋,푸시하겠습니다

2024-07-08 11:25 UTC, yhames submitted a review, later dismissed
고생하셨습니다!

2024-07-09 02:43 UTC, AreSain approved these changes
LGTM

2024-07-09 02:43 UTC, yhames approved these changes
고생하셨습니다!

2024-07-09 02:45 UTC, merged