✨ [Feature] #861 Agenda 종료 확정하기 API
42organization/42gg.server.dev.v2 pull request #883
Opened 2024-07-12 05:01 UTC by yhames

## 📌 개요 
  - 대회 시상 및 확정하기 API
    - 시상 대회인 경우 시상하고 확정
    - 시상하지 않는 대회인 경우 시상 없이 확정
 ## 💻 작업사항 
  - confirmAgenda 추가 (Controller, Service)
  - 리펙토링
    - Service에서 ResponseDto에 대한 의존성 제거
  - 테스트코드 추가
 ## ✅ 변경로직 
  - Agenda 상세조회시 공지사항이 없는 경우 `null -> 빈 문자열`로 변경
 ## 💡Issue 번호 
 - closed #861

2024-07-12 11:13 UTC, AreSain requested changes
request랑 response dto 이름 짓는 부분에서 일관성이 부족한 것 같습니다. 다같이 모여서 req와 res로 할지, 풀 네임을 붙일지 폴더구조로 구분할지 정해야할 것 같아요!

2024-07-12 12:23 UTC, AreSain commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaTeamAwardDto.java
> +	@NotNull
여기서 @Valid 어노테이션은 사용되고있지 않습니다!

2024-07-12 15:43 UTC, yhames commented
> request랑 response dto 이름 짓는 부분에서 일관성이 부족한 것 같습니다. 다같이 모여서 req와 res로 할지, 풀 네임을 붙일지 폴더구조로 구분할지 정해야할 것 같아요!

제가 인지 못했던것 같습니다.
req와 res로 수정 완료했습니다.

2024-07-12 15:43 UTC, yhames commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
> +		return ResponseEntity.status(HttpStatus.CREATED).body(responseDto);
201로 수정했습니다!

2024-07-12 15:43 UTC, yhames commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/request/AgendaTeamAwardDto.java
> +	@NotNull
`@Valid` 적용하는 방식으로 변경했습니다!

2024-07-12 15:43 UTC, yhames commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agenda/controller/AgendaController.java
> +		@ApiResponse(responseCode = "203", description = "Agenda 참가 신청 성공"),
수정 완료했습니다!

2024-07-15 02:23 UTC, AreSain approved these changes
고생 많으셨습니다.

2024-07-15 02:25 UTC, kimjieun0301 approved these changes
고생하셨습니다

2024-07-15 02:32 UTC, merged