✨ [Feature] #853 개인 프로필 변경 API
42organization/42gg.server.dev.v2 pull request #891
Opened 2024-07-16 06:01 UTC by kimjieun0301

## 📌 개요 
  - 개인 프로필 변경 API
 ## 💻 작업사항 
  -개인 프로필 변경 API
 ## 💡Issue 번호 
 - closed #853

2024-07-16 06:36 UTC, AreSain commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/controller/request/AgendaProfileChangeReqDto.java
> +	@NotBlank
@NotNull @NotEmpty @NotBlank 중에 하나만 쓰시면 됩니다.
낫널은 널만 금지
낫엠티는 널 + ""금지
낫블랭크는 널 + "" + " " 금지입니다

2024-07-17 02:50 UTC, yhames requested changes

2024-07-17 02:50 UTC, yhames commented on gg-agenda-api/src/main/java/gg/agenda/api/user/agendaprofile/service/AgendaProfileModifyService.java
> +public class AgendaProfileModifyService {
CUD 서비스 통합을 위해 서비스 클래스 이름에 Modify 제거

2024-07-17 02:50 UTC, yhames commented on gg-agenda-api/src/test/java/gg/agenda/api/user/agendaprofile/AgendaProfileControllerTest.java
> +			mockMvc.perform(patch("/agenda/profile")
검증 로직 추가 부탁드립니다!

2024-07-19 07:40 UTC, AreSain approved these changes
LGTM

2024-07-22 02:28 UTC, yhames approved these changes
고생하셨습니다!

2024-07-22 02:43 UTC, merged