✨ [Feature] Admin 티켓 수정 API #946
42organization/42gg.server.dev.v2 pull request #975
Opened 2024-08-22 06:01 UTC by kimjieun0301

## 📌 개요 
  -Admin 티켓 수정 API 
  -datetime format 수정
  -AgendaTeam Admin content 필드 추가(yhames)
  -agendaprofile /info 주석 변경
  -agendaprofile 내가 참여했던/참여중인 대회 response에 agenda key 추가
 ## 💻 작업사항 
  -Admin 티켓 수정 API 
  -datetime format 수정
  -AgendaTeam Admin content 필드 추가(yhames)
  -agendaprofile /info 주석 변경
  -agendaprofile 내가 참여했던/참여중인 대회 response에 agenda key 추가
 ## 💡Issue 번호 
 - closed #946

2024-08-22 06:55 UTC, yhames requested changes

2024-08-22 06:55 UTC, yhames commented on gg-data/src/main/java/gg/data/agenda/Ticket.java
> +	public void updateTicketAdmin(UUID issuedFrom, UUID usedTo, Boolean isApproved, LocalDateTime approvedAt,
null값이 할당되는 경우 JPA에서 예외가 발생하나요?

2024-08-22 09:04 UTC, kimjieun0301 commented on gg-data/src/main/java/gg/data/agenda/Ticket.java
> +	public void updateTicketAdmin(UUID issuedFrom, UUID usedTo, Boolean isApproved, LocalDateTime approvedAt,
엇 아뇨!!

2024-08-23 06:14 UTC, yhames approved these changes
감사합니다!

2024-08-23 06:14 UTC, merged